---
- name: Rollback
  hosts: nodejs-app
  remote_user: root
  become: yes
  become_user: root
  vars:
    nodejs_user: node
    nodejs_group: node
    nodejs_home_path: "/home/{{ nodejs_user }}"

  roles:
    - rollback