---
- name: NodeJS
  hosts: nodejs-app
  remote_user: root
  become: yes
  become_user: root
  vars:
    nodejs_user: node
    nodejs_group: node
    nodejs_home_path: "/home/{{ nodejs_user }}"

  roles:
    - nodejs

- name: PM2
  hosts: pm2-app
  remote_user: root
  become: yes
  become_user: root
  vars:
    nodejs_user: node
    nodejs_group: node
    nodejs_home_path: "/home/{{ nodejs_user }}"

  roles:
    - pm2

- name: deploy
  hosts: nodejs-app
  remote_user: root
  become: yes
  become_user: root
  vars:
    nodejs_user: node
    nodejs_group: node
    nodejs_home_path: "/home/{{ nodejs_user }}"
    app_name: helloworld

  roles:
    - deploy

- name: nginx-proxy
  hosts: nodejs-app
  become: true
  roles:
    - nginxinc.nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        conf_file_location: /etc/nginx/conf.d/
        conf_file_name: proxy.conf
        template_file: http/default.conf.j2
        port: "80 default_server"
        server_name: "_"
        error_page: /usr/share/nginx/html
        proxy_pass: backend
        load_balancer:
          proxy_pass: backend
          health_check_plus: false
        upstreams:
          upstream1:
            name: backend
            lb_method: least_conn
            zone_name: backend
            zone_size: 64k
            sticky_cookie: false
            servers:
              server1:
                address: localhost
                port: 3000
                weight: 1
                health_check: max_fails=3 fail_timeout=5s

- name: nginx-proxy-ssl
  hosts: nodejs-app
  become: true
  roles:
    - nginxinc.nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        conf_file_location: /etc/nginx/conf.d/
        conf_file_name: proxy-ssl.conf
        template_file: http/default.conf.j2
        port: 443
        server_name: "*.example.com.br *.example.com.br"
        error_page: /usr/share/nginx/html
        proxy_pass: backend-ssl
        ssl:
          cert: default.crt
          key: default.key
        load_balancer:
          proxy_pass: backend-ssl
          health_check_plus: false
        upstreams:
          upstream1:
            name: backend-ssl
            lb_method: least_conn
            zone_name: backend-ssl
            zone_size: 64k
            sticky_cookie: false
            servers:
              server1:
                address: localhost
                port: 3000
                weight: 1
                health_check: max_fails=3 fail_timeout=5s
      