---
- name: DEPLOY-APP | Configure
  import_tasks: config.yml
  tags:
    - configure

- name: DEPLOY-APP | Backup
  import_tasks: backup.yml
  tags:
    - backup

- name: DEPLOY-APP | deploy
  import_tasks: deploy.yml
  tags:
    - deploy
